DROP TABLE Users CASCADE CONSTRAINTS;
DROP SEQUENCE users_id_sequence;

DROP TABLE Cities CASCADE CONSTRAINTS;
DROP SEQUENCE cities_id_sequence;

DROP TABLE Organizations CASCADE CONSTRAINTS;
DROP SEQUENCE organizations_id_sequence;

DROP TABLE Drivers CASCADE CONSTRAINTS;
DROP SEQUENCE drivers_id_sequence;

DROP TABLE Goods CASCADE CONSTRAINTS;
DROP SEQUENCE goods_id_sequence;

DROP TABLE Orders CASCADE CONSTRAINTS;
DROP SEQUENCE orders_id_sequence;

DROP TABLE DriversOrders CASCADE CONSTRAINTS;

DROP TABLE Ways CASCADE CONSTRAINTS;
DROP SEQUENCE ways_id_sequence;

DROP TABLE Routes CASCADE CONSTRAINTS;
DROP SEQUENCE routes_id_sequence;